spring:
  application:
    name: HopitalPlanningProject

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_planning?useSSL=false&allowPublicKeyRetrieval=true
    username: root  # Mets ton utilisateur MySQL
    password: root  # Mets ton mot de passe MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # Pour créer/modifier les tables automatiquement
    show-sql: true  # Afficher les requêtes SQL dans la console


server:
  port: 8080  # Port de ton serveur Spring Boot
