spring:
  application:
    name: HopitalPlanningProject

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_planning2?useSSL=false&serverTimezone=UTC
    username: root  # Mets ton utilisateur MySQL
    password: root  # Mets ton mot de passe MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080  # Port de ton serveur Spring Boot
